### ISSUE TITLE
support for .appref-ms apps?

### ISSUE THREAD

**Issue by vasily-v-ryabov** [vasily-v-ryabov/pywinauto-64#9]
This is a copy of issue 15 from google code repo: https://code.google.com/p/pywinauto/issues/detail?id=15

1. Attempt to start an app using start_ command, like app.start_('c:\foo\foo.appref-ms')
 
app starts and app object references to Application's main window.

latest, on winXP

command:

>>> app.start_ ('c:\Documents and Settings\navaoma\Desktop\Automation\Foo.appref-ms')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python25\lib\site-packages\pywinauto\application.py", line 876, in st
art_
    raise AppStartError(message)
pywinauto.application.AppStartError: Could not create the process "c:\Documents
and Settings
avaoma\Desktop\Automation\Foo.appref-ms"
Error returned by CreateProcess: [Error 2] The system cannot find the file speci
fied.
>>>

**Comment by vasily-v-ryabov** [comment]
Related question on StackOverflow: http://stackoverflow.com/questions/29199827/start-clickonce-application-through-createprocess

**Comment by vasily-v-ryabov** [comment]
Possible workaround:

    p = subprocess.Popen(['cmd.exe', '/c', r'<full_path>\GitHub.appref-ms'])
    app = pywinauto.Application.connect(path='github.exe')

Seems there's no way to find .exe full path and name programmatically.
